name: Laravel Package Tests

on:
  push:
    branches:
      - master
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, sqlite3, pdo_sqlite
          coverage: none

      # Step 2: Install Laravel
      - name: Install Laravel
        run: |
          composer global require laravel/installer
          export PATH="$HOME/.config/composer/vendor/bin:$PATH"
          laravel new laravel-appointments

      # Step 3: Install Composer dependencies
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      # Step 4: Setup Laravel environment
      - name: Setup Laravel environment
        run: |
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "APP_URL=http://localhost" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/tmp/testing.sqlite" >> .env
          touch /tmp/testing.sqlite
          php artisan config:clear
          php artisan migrate --force

      # Step 5: Run PHPUnit tests
      - name: Run tests
        run: |
          vendor/bin/phpunit --testdox
