name: Test Laravel Package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: matriphe/laravel-pkg-test-action@v2
      with:
        laravel_install_args: --prefer-dist
        package_install_args: --prefer-dist --no-progress